version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      build:
        context: .
        dockerfile: ./app/Dockerfile
      volumes:
        - ./app/code:/var/www/html
        - /var/www/html/vendor
